version: "3.9"

services:
  # Backend FastAPI
  web:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Django
  django:
    build: ./frontend
    container_name: django_app
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - web
      - db
    command: python manage.py runserver 0.0.0.0:8001

  # PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Testes automáticos FastAPI
  test:
    build: ./backend
    command: ["pytest"]
    volumes:
      - ./backend:/backend

  # Linter FastAPI
  lint:
    build: ./backend
    command: flake8 .
    volumes:
      - ./backend:/backend

volumes:
  postgres_data:
  pgadmin_data:
